import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const actions = readFileSync(new URL('../../src/app/hoje/checklist-actions.ts', import.meta.url), 'utf8');
const component = readFileSync(new URL('../../src/app/hoje/TodayChecklist.tsx', import.meta.url), 'utf8');
const focusTimer = readFileSync(new URL('../../src/app/hoje/FocusTimer.tsx', import.meta.url), 'utf8');
const page = readFileSync(new URL('../../src/app/hoje/page.tsx', import.meta.url), 'utf8');
const conversaPage = readFileSync(new URL('../../src/app/conversa/page.tsx', import.meta.url), 'utf8');
const conversaPanel = readFileSync(new URL('../../src/app/conversa/ConversationPanel.tsx', import.meta.url), 'utf8');
const scheduleAction = readFileSync(new URL('../../src/app/conversa/schedule-task-action.ts', import.meta.url), 'utf8');

assert.ok(actions.includes("'use server'"));
assert.ok(actions.includes(".eq('user_id', userId)"));
assert.ok(actions.includes(".eq('status', 'pending')"));
assert.ok(actions.includes(".eq('needs_confirmation', false)"));
assert.ok(actions.includes(".gte('deadline_at', start.utc.toISOString())"));
assert.ok(actions.includes(".lt('deadline_at', end.utc.toISOString())"));
assert.ok(actions.includes('isValidTimeZone(timeZone)'));
assert.ok(!actions.includes('service_role'));
assert.ok(!actions.includes('createAdminClient'));

assert.ok(component.includes('Checklist do dia'));
assert.ok(component.includes('Para fazer hoje, sem horário marcado'));
assert.ok(component.includes('Decida em um toque o que merece sua atenção.'));
assert.ok(component.includes('Fazer hoje'));
assert.ok(component.includes('Urgente + importante'));
assert.ok(component.includes('Planejar'));
assert.ok(component.includes('Delegar'));
assert.ok(component.includes('Depois'));
assert.ok(component.includes('setTaskPriority(taskId, priority)'));
assert.ok(component.includes('completeTask(taskId)'));
assert.ok(component.includes('state.items.filter((item) => item.id !== taskId)'));
assert.ok(component.includes('Agendar horário'));
assert.ok(component.includes('/conversa?agendarTask='));
assert.ok(component.includes('encodeURIComponent(item.id)'));
assert.ok(!component.includes('encodeURIComponent(item.title)'));
assert.ok(component.includes("import { FocusTimer } from './FocusTimer'"));
assert.ok(component.includes('<FocusTimer'));
assert.ok(component.includes('onDone={() => void markDone(item.id)}'));
assert.ok(!component.includes('Google Calendar'));
assert.ok(!component.includes('create_event'));

assert.ok(focusTimer.includes("'use client'"));
assert.ok(focusTimer.includes('Foco 25 min'));
assert.ok(focusTimer.includes('50 min'));
assert.ok(focusTimer.includes('Date.now() + minutes * 60_000'));
assert.ok(focusTimer.includes('(targetEndsAt - Date.now()) / 1000'));
assert.ok(focusTimer.includes('window.setInterval(updateRemaining, 1000)'));
assert.ok(focusTimer.includes('window.clearInterval(interval)'));
assert.ok(focusTimer.includes('Tempo de foco concluído.'));
assert.ok(focusTimer.includes('Concluiu “{taskTitle}”?'));
assert.ok(focusTimer.includes('onClick={onDone}'));
assert.ok(focusTimer.includes('+25 min'));
assert.ok(focusTimer.includes('Parar'));
assert.ok(!focusTimer.includes('localStorage'));
assert.ok(!focusTimer.includes('sessionStorage'));
assert.ok(!focusTimer.includes('fetch('));
assert.ok(!focusTimer.includes('supabase'));
assert.ok(!focusTimer.includes('Google'));

assert.ok(scheduleAction.includes("'use server'"));
assert.ok(scheduleAction.includes('getClaims()'));
assert.ok(scheduleAction.includes(".eq('id', taskId.trim())"));
assert.ok(scheduleAction.includes(".eq('user_id', userId)"));
assert.ok(scheduleAction.includes(".eq('status', 'pending')"));
assert.ok(scheduleAction.includes(".eq('needs_confirmation', false)"));
assert.ok(scheduleAction.includes(".select('title')"));
assert.ok(!scheduleAction.includes('service_role'));
assert.ok(!scheduleAction.includes('createAdminClient'));

assert.ok(conversaPage.includes('<ConversationPanel />'));
assert.ok(!conversaPage.includes('agendarTask'));
assert.ok(!conversaPage.includes('resolveScheduleTask'));

assert.ok(conversaPanel.includes("new URLSearchParams(window.location.search).get('agendarTask')"));
assert.ok(conversaPanel.includes('resolveScheduleTask(taskId)'));
assert.ok(conversaPanel.includes("setScheduleTaskTitle(task.status === 'ok' ? task.title : '')"));
assert.ok(conversaPanel.includes("scheduleTaskTitle ? 'Que horário?'"));
assert.ok(conversaPanel.includes('Diga o horário. Ex.: “15 horas” ou “amanhã às 9”.'));
assert.ok(conversaPanel.includes("const defaultDayLabel = scheduleDefaultDay === 'tomorrow' ? 'amanhã' : 'hoje'"));
assert.ok(conversaPanel.includes('`Agende ${scheduleTaskTitle} ${defaultDayLabel} às ${trimmed}`'));
assert.ok(conversaPanel.includes("const isConfirmation = /^(sim|n[aã]o)\\s*[.!?,;]*$/iu.test(trimmed)"));
assert.ok(conversaPanel.includes('scheduleTaskTitle && !proposalVisible && !alreadyExplicit && !isConfirmation'));
assert.ok(conversaPanel.includes('sendConversationMessage(\n          backendText,\n          Intl.DateTimeFormat().resolvedOptions().timeZone'));
assert.ok(conversaPanel.includes('sendConversationMessage(text, timezone)'));
assert.ok(conversaPanel.includes('setText(transcript.slice(0, 10000))'));
assert.ok(!conversaPanel.includes('useState<string | null>'));
assert.equal((conversaPanel.match(/let active = true;/g) ?? []).length, 1);
assert.ok(conversaPanel.includes('if (active) {\n          setBootstrapping(false);\n        }'));
assert.ok(!conversaPanel.includes('access_token'));
assert.ok(!conversaPanel.includes('refresh_token'));
assert.ok(!conversaPanel.includes('service_role'));
assert.ok(!conversaPanel.includes('localStorage'));
assert.ok(!conversaPanel.includes('sessionStorage'));

assert.ok(page.includes("import { TodayChecklist } from './TodayChecklist'"));
assert.ok(page.includes('<TodayChecklist />'));

console.log('[PASS] checklist do dia usa apenas tarefas pendentes e confirmadas do usuário');
console.log('[PASS] recorte de hoje respeita timezone civil do aparelho');
console.log('[PASS] Eisenhower é apresentado em linguagem simples e resolvido em um toque');
console.log('[PASS] agendar horário envia só id opaco e resolve título no servidor por usuário');
console.log('[PASS] agendamento assistido aceita hoje/amanhã sem expor lógica de agenda no cliente');
console.log('[PASS] foco de 25/50 min é local, sem banco, sem agenda e corrige drift por Date.now');
console.log('[PASS] ao terminar o foco, concluir continua sendo uma ação explícita do usuário');
console.log('[PASS] bootstrap, timezone e transcrição por voz preservam os contratos existentes');
